Final result - last details fixed
WildCodeSchool/2023-02-JS-Lille-project-2-groupe4 pull request #14
Opened 2023-05-03 12:20 UTC by Romain-Constant

2023-05-03 21:26 UTC, Sax593 requested changes

2023-05-03 21:26 UTC, Sax593 commented on frontend/src/components/inmemoriam/InMemoriam.module.css
> +  margin-bottom: 20px;
Unecessary space

2023-05-03 21:26 UTC, Sax593 commented on frontend/src/components/inmemoriam/astronautCard/AstronautCard.module.css
> +  display: flex;
unecessary space

2023-05-03 21:26 UTC, Sax593 commented on frontend/src/components/nextLaunch/NextLaunchContainer.jsx
> +        </div>{" "}
{" "} unecessary

2023-05-03 21:26 UTC, Sax593 commented on package.json
> +    "react-router-dom": "^6.10.0"
It's front end package, please intall this in frontend package.json

2023-05-04 09:39 UTC, Romain-Constant commented
Changes done !

2023-05-04 11:33 UTC, Sax593 approved these changes

2023-05-04 12:11 UTC, JocelynDeloose approved these changes

2023-05-04 12:11 UTC, merged